server:
  port: 8082

spring:
  profiles: test
  application:
    name: mytest-pro
  datasource:
    hikari:
      master:
        jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT
        username: root
        password: root
        auto-commit: false
        connection-timeout: 30000
        connection-test-query: SELECT 1
        idle-timeout: 600000
        minimum-idle: 50
        max-lifetime: 180000
        maximum-pool-size: 50
        pool-name: master-hikari-pool
      slave:
        jdbc-url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT
        username: root
        password: root
        auto-commit: false
        connection-timeout: 30000
        connection-test-query: SELECT 1
        idle-timeout: 600000
        minimum-idle: 30
        max-lifetime: 180000
        maximum-pool-size: 30
        pool-name: master-hikari-pool
